# Device-specific extra includes
#
SYSTEM_INCLUDES=`echo  	`


# Uncomment the following, if device provides File-System-Implementation.
#
#FS_COMMUNICATION_IMPL="Y"


# Uncomment the following, if device is a GSM-device.
# Uncommenting this, causes the device to wait for a SMS from the InstaMsg-server, containing the following params ::
#
# 		APN
# 		APN-Username
# 		APN-Password
#
# Above parameters are required to make a connection to the Mobile-APN.
#
#IS_GSM_DEVICE="Y"


# Uncomment the following, if the socket-implementation provided by the device is secured.
#
#IS_SSL="Y"


# Device-specific extra source-files.
#
EXTRA_SOURCES=`echo   `


# Device-specific extra object-files that need to linked.
#
EXTRA_OBJECT_FILES=`echo   `


# Compile-cum-Link command for the platform.
#
COMPILE_COMMAND=""


# Any final commands that need to be run.
#
declare -a FINAL_COMMANDS=("command-1" "command-2" "command-3")
