APP_SOURCES=`echo                                                                                   \
        	common/apps/subscriber/main.c                                                           \
			common/apps/utils/publisher_subscriber_init.c											`

