APP_SOURCES=`echo                                                                                   \
        	common/apps/subscriber/main.c                                                           `

