APP_SOURCES=`echo                                                                                   \
        	common/apps/media_streamer/main.c                                                       `

