APP_SOURCES=`echo                                                                                   \
        	common/apps/one_to_one_peer/main.c                                                      `

