APP_SOURCES=`echo                                                                                   \
        	common/apps/one_to_one_initiator/main.c                                                 \
			common/apps/utils/publisher_subscriber_init.c											`

