APP_SOURCES=`echo                                                                                   \
        	common/apps/ioeye/main.c                                                                \
        	common/apps/ioeye/hex.c                                                                 \
        	common/apps/ioeye/modbus.c                                                              \
        	common/apps/ioeye/adc.c                                                              	\
            	                                                                                    \
        	device/VENDOR/apps/ioeye/device_modbus.c                                             	\
        	device/VENDOR/apps/ioeye/device_adc.c                                             		\
        	device/VENDOR/apps/ioeye/device_time.c                                               	\
        	device/VENDOR/apps/ioeye/device_data_logger.c                                        	`

APP_COMPILER_DIRECTIVES=`echo																		\
						-DMODBUS_INTERFACE_ENABLED													`
