APP_SOURCES=`echo                                                                                   \
        	common/apps/publisher/main.c                                                            \
			common/apps/utils/publisher_subscriber_init.c											`

