APP_SOURCES=`echo                                                                                   \
        	common/apps/publisher/main.c                                                            `

