APP_SOURCES=`echo                                                                                   \
        	apps/ioeye/main.c                                                                       \
        	apps/ioeye/hex.c                                                                        \
        	apps/ioeye/modbus.c                                                                     \
            	                                                                                    \
        	device/VENDOR/apps/ioeye/device_modbus.c                                             	\
        	device/VENDOR/apps/ioeye/device_time.c                                               	\
        	device/VENDOR/apps/ioeye/device_data_logger.c                                        	`

