APP_SOURCES=`echo                                                                                   \
        	common/apps/streaming/main.c                                                            `

