APP_SOURCES=`echo                                                                                   \
        	common/apps/storage-debugger-driver/main.c                                              `

